### ISSUE TITLE
Nintendo 64 controls not set

### ISSUE THREAD

**Issue by Atrain111** [tonymorris/arcade#13]
The controls on the Nintendo 64 are not set. The emulator uses the Logitech controller not the Nintendo controllers. The left and right controls on the Logitech controller are on the D-Pad and not the joystick.

**Comment by tonymorris** [comment]
Controls are set by `/usr/share/games/mupen64plus/InputAutoCfg.ini` which overwrites `~/.config/mupen64plus/mupen64plus.cfg`. Manual setting (which inhibits this overwriting) can be configured by setting `mode = 0` for each controller in `~/.config/mupen64plus/mupen64plus.cfg`.

Commit 2858102ff681fa5ed07d926a7dca2b7c7a87a896 configured `mupen64plus` for a single Logitech F710 controller.
